USE Lab20;

CREATE TABLE IF NOT EXISTS cars (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, vin CHAR(17), manufacturer VARCHAR(20),
       model VARCHAR(20), year YEAR, color VARCHAR(20));
       
CREATE TABLE IF NOT EXISTS customers (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, customer_id MEDIUMINT, name VARCHAR(40),
phone VARCHAR(20), email VARCHAR(50), city VARCHAR(20), state VARCHAR(20), country VARCHAR(20), zip MEDIUMINT);

CREATE TABLE IF NOT EXISTS salespersons (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, staff_id SMALLINT,
name VARCHAR(40), store VARCHAR(40));

CREATE TABLE IF NOT EXISTS invoice (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, invoice_number MEDIUMINT,
date DATE, car_id INT, customer_id INT, salesperson_id INT);